apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: 
  name: test-secret
spec: 
  refreshInterval: 15s
  secretStoreRef:
    name: vault-ss
    kind: SecretStore
  target:
    name: created-secret
    creationPolicy: Owner
  data: 
  - secretKey: test-key
    remoteRef:
      key: data/test-secret
      property: data/key
