apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-ss
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: "vault-test"
          role: "eso-sa"
          serviceAccountRef: 
            name: eso-ss
      path: kv/data
      server: http://10.10.30.98:8200
      version: v1
