apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldapidm-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: centralis-sso
  target:
    name: ldapidm-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: IDM_SECRET