---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso

resources:
  - gitops/rhsso/operator/base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: rhsso-operator
